### ISSUE TITLE
Export chat history

### ISSUE THREAD

**Issue by gapop** [wireapp/wire#116]
Please allow users to export conversations. WhatsApp has this, and I think it's important for any messaging system that's used for serious exchanges.

**Comment by fonixer** [comment]
I would appreciate this feature a lot.
When I met my now girlfriend online, I picked Wire. 
I wanted private conversations and I never thought that this girl wouldn't leave me after few weeks.
Now, I have almost a year of conversations with her and no way to save it. 
I have to change some of the devices. I have some older ones, but they just won't load the conversations. And even if they could do that after hours of loading, a lot of the chat history would be missing. 
I understand why there is no chat history on a new device. It's a great feature and consequence of the way Wire was build. 
I would just like to export all the available chat history and maybe images. Just to backup them and have them store somewhere since it's a huge part of my life. Maybe even the most important one since we're getting married soon.
Maybe there is a way for me to do it myself without incorporating it into Wire? Maybe some JavaScript would handle it since all of the information I have is in the webapp and the Android version on my older phone?
I just don't know where to start.

**Comment by gapop** [comment]
@fonixer, if you are a programmer, I can suggest a starting point. The Web app stores the data in the browser's Indexed DB. Go to the Web app and open your browser's dev console. In Firefox, if I go to Storage / Indexed DB, under the default / events key I can see the message objects. You'll have to figure out the DB structure, but the data should be there. You could write a browser extension to save that data. Also, since the browser stores the data in a SQLite database (at least Firefox does), you could write a standalone program that extracts it from there.

**Comment by trymeouteh** [comment]
+1

**Comment by kristin-wire** [comment]
This feature is on our roadmap for 2018, but no specifics to share just yet.

We have logged this in our internal feature request database for tracking, and will close this request here.

**Comment by mydexterid** [comment]
Unfortunately this will never be implemented:
https://medium.com/@wireapp/history-backup-comes-to-wire-cd79e02ec66e

**Comment by moe-rs** [comment]
Hi @kristin-wire, any updates on this feature?

**Comment by marcoconti83** [comment]
Hi @moe-rs ,
since this ticket was opened, we added history backup in Wire. This is done manually, and allows you to restore the history from a device of the same type (e.g. from iOS to iOS, from Android to Android, from web to web).

**Comment by moe-rs** [comment]
Hello @marcoconti83, 

I did see that feature "history backup" but that is not what this ticket was requesting which is "Export chat history" similar to What'sApp where it essentially dumps a specific conversation with someone into a simple human readable text file (media is optional). 

Thanks!

**Comment by mischa72** [comment]
This feature would interest me a lot too. I would like to export a year of conversation and retrieve all shared pics. I would like to have them available on my phone or other device without having to save about 3500 pics manually. I understand you want to keep the platform safe, but after login users should be able to download their own stuff without any limitations.

**Comment by Neopopulas** [comment]
One more for this. Even AIM used to have this option, you just right-click and save-as and its that easy. I'm not sure why so few probrams can do this now.

**Comment by OmeGak** [comment]
Here's a Gist to export Wire channels from the web application:
https://gist.github.com/OmeGak/f193c5459bccdadb2e339e093668dbf5

Thanks for the idea @gapop!

**Comment by dkovacevic** [comment]
We have a tool that can convert your backup file into set of PDF files (separate file per conversation)
https://github.com/wireapp/backup-export-tool

PDF should look (and feel) like Wire.

<img width="615" alt="Screenshot 2020-09-27 at 20 57 41" src="https://user-images.githubusercontent.com/4378852/94373217-25c38680-0104-11eb-830d-6af154b764a0.png">

**Comment by torse** [comment]
Unfortunately the export tool doesn't work for me. I've backup a the very important chat to a file "XXX_wbu" and used the tool with the secured backup password and, as this didn't work, with my login password. Below are the two respective error messages. 

Also the backup is only 56kb although there are a few images and paintings ( :heart: ) in that chat. Strange, no?

with backup password:
```
$ java -jar backup-export.jar android "Wire-XXXX.android_wbu" --email "xxx@yyy.zz" --password "xxxxxxxxx"
Backup to PDF converter version: 2.0.0
Backup to PDF converter version: 2.0.0

AuthException: code: 403, msg: {"code":403,"label":"invalid-credentials","message":"Authentication failed"}, label: null
	at com.wire.helium.LoginClient.login(LoginClient.java:104)
	at com.wire.helium.LoginClient.login(LoginClient.java:81)
	at com.wire.backups.exports.utils.InstantCache.<init>(InstantCache.java:35)
	at com.wire.backups.exports.exporters.AndroidExporter.run(AndroidExporter.java:41)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:27)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:9)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.wire.backups.exports.Service.main(Service.java:15)
```
with login password:
```
$ java -jar backup-export.jar android "Wire-XXXX.android_wbu" --email "xxx@yyy.zz" --password "xxxxxxxxx"
Backup to PDF converter version: 2.0.0

May 11, 2023 8:56:35 PM com.wire.xenon.tools.Logger error
SEVERE: InstantCache.getUserId: username: , ex: HttpException: code: 404, msg: {"code":404,"label":"no-endpoint","message":"The requested endpoint does not exist"}, label: null
HttpException: code: 404, msg: {"code":404,"label":"no-endpoint","message":"The requested endpoint does not exist"}, label: null
	at com.wire.helium.API.getUserId(API.java:419)
	at com.wire.backups.exports.utils.InstantCache.getUserId(InstantCache.java:41)
	at com.wire.backups.exports.exporters.AndroidExporter.run(AndroidExporter.java:42)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:27)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:9)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.wire.backups.exports.Service.main(Service.java:15)
java.lang.IllegalStateException: It was not possible to obtain user id! Check for other errors.
	at com.wire.backups.exports.exporters.AndroidExporter.run(AndroidExporter.java:44)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:27)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:9)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
```

**Comment by andredasilvapinto** [comment]
It also breaks for me:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Byte` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (File); line: 1, column: 1160053] (through reference chain: java.lang.Object[][2930]->com.wire.backups.exports.exporters.DesktopExporter$Event["data"]->com.wire.backups.exports.exporters.Desk at [Source: (File); line: 1, column: 1160053] (through reference chain: java.lang.Object[][2930]->com.wire.backups.exports.exporters.DesktopExporter$Event["data"]->com.wire.backups.exports.exporters.Desk	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1590)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$ByteDeserializer._parseByte(NumberDeserializers.java:302)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$ByteDeserializer.deserialize(NumberDeserializers.java:273)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$ByteDeserializer.deserialize(NumberDeserializers.java:250)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:213)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3388)
	at com.wire.backups.exports.exporters.DesktopExporter.run(DesktopExporter.java:80)
	at com.wire.backups.exports.commands.OpenClientCommand.call(OpenClientCommand.java:104)
	at com.wire.backups.exports.commands.WebClientCommand.call(WebClientCommand.java:10)
	at com.wire.backups.exports.commands.OpenClientCommand.call(OpenClientCommand.java:18)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.wire.backups.exports.Service.main(Service.java:15)
```

I can see some content in the output folder (especially in events.json), but it doesn't seem complete.

A simple dump to text would be better, as long as it works reliably.
